feat: add notifications to the demo page
backstage/demo pull request #366
Opened 2024-04-03 19:04 UTC by drodil

Adds notifications to the demo page (even though there are no plugins sending them yet but just to give idea what it looks like)

2024-04-05 23:18 UTC, awanlin requested changes
Thanks for this @drodil, this makes sense to me. My only concern is that Notifications are still in an alpha stage so I think we should at least mention that.

2024-04-05 23:18 UTC, awanlin commented on README.md
> +- [Notifications](https://demo.backstage.io/notifications)
Can you create an Alpha subheading in this section? As Notifications is pretty new I think that makes more sense to me. Can we also perhaps include a link to the related BEP?

2024-07-04 12:39 UTC, awanlin requested changes
Hi @drodil, can you rebase to resolve the conflicts? Then I can approve and merge this in 👍

2024-08-06 11:55 UTC, awanlin commented
Hi @drodil, any chance you can rebase to resolve the conflict? Then we can merge it in. 🚀

2024-08-07 05:07 UTC, drodil commented
@awanlin rebased!

2024-08-07 12:12 UTC, awanlin approved these changes

2024-08-07 12:12 UTC, merged